import type {
  Account,
  AIInsight,
  Alert,
  BankConnection,
  Bill,
  Budget,
  BudgetPeriod,
  Category,
  Debt,
  ManualFinanceItem,
  NetWorthSnapshot,
  AppNotification,
  OverdraftPlan,
  PaydayPlan,
  SavingsGoal,
  NotificationPreference,
  NotificationRule,
  PushSubscriptionRecord,
  Subscription,
  Transaction,
  UserProfile,
} from "@/lib/domain";
import {
  calculateBillsDueBeforePayday,
  calculateBillsAccountBalance,
  calculateBudgetHealth,
  calculateCashflowAccountBalance,
  calculateDebtPaymentsDueBeforePayday,
  calculateDebtSummary,
  calculateLinkedSavingsGoalBalance,
  calculateMonthlyIncome,
  calculateMonthlySpending,
  calculateNetWorth,
  calculateProjectedMonthEndBalance,
  calculateSafeToSpendAmount,
  calculateSafeToSpendEligibleCash,
  calculateSavingsGoalProgress,
  calculateTotalAssets,
  calculateTotalCurrentCash,
  calculateTotalLiabilities,
  getConnectionLifecycleStatus,
  getUpcomingBillItems,
  getUpcomingManualCashflowItems,
  type BudgetHealthItem,
  type Tone,
} from "@/lib/finance";
import { formatDateShort } from "@/lib/format";
import {
  createDefaultNotificationPreferences,
  generateFinanceNotifications,
} from "@/lib/notifications";

export type BudgetCategory = BudgetHealthItem;

const userId = "user_mock_001";
const createdAt = "2026-06-30T09:00:00.000Z";

export const mockUserProfile: UserProfile = {
  id: userId,
  displayName: "Demo User",
  locale: "en-GB",
  currency: "GBP",
  paydayDayOfMonth: 25,
  minimumBuffer: 350,
  createdAt,
  updatedAt: createdAt,
};

export const mockBankConnections: BankConnection[] = [
  {
    id: "conn_amex",
    provider: "mock",
    institutionName: "American Express",
    institutionId: "amex",
    status: "connected",
    consentStatus: "active",
    consentStartedAt: "2026-06-01T09:00:00.000Z",
    consentExpiresAt: "2026-09-01T09:00:00.000Z",
    lastSyncedAt: createdAt,
    errorMessage: null,
    createdAt: "2026-06-01T09:00:00.000Z",
    updatedAt: createdAt,
  },
  {
    id: "conn_nationwide",
    provider: "mock",
    institutionName: "Nationwide",
    institutionId: "nationwide",
    status: "syncing",
    consentStatus: "active",
    consentStartedAt: "2026-06-01T09:00:00.000Z",
    consentExpiresAt: "2026-09-01T09:00:00.000Z",
    lastSyncedAt: "2026-06-30T08:58:00.000Z",
    errorMessage: null,
    createdAt: "2026-06-01T09:00:00.000Z",
    updatedAt: createdAt,
  },
  {
    id: "conn_revolut",
    provider: "mock",
    institutionName: "Revolut",
    institutionId: "revolut",
    status: "connected",
    consentStatus: "expired",
    consentStartedAt: "2026-03-01T09:00:00.000Z",
    consentExpiresAt: "2026-06-20T09:00:00.000Z",
    lastSyncedAt: "2026-06-20T08:45:00.000Z",
    errorMessage: null,
    createdAt: "2026-03-01T09:00:00.000Z",
    updatedAt: "2026-06-20T08:45:00.000Z",
  },
  {
    id: "conn_mock_failed",
    provider: "mock",
    institutionName: "Mock Sandbox Failure",
    institutionId: "mock_failed",
    status: "sync_failed",
    consentStatus: "active",
    consentStartedAt: "2026-06-10T09:00:00.000Z",
    consentExpiresAt: "2026-09-10T09:00:00.000Z",
    lastSyncedAt: "2026-06-29T07:30:00.000Z",
    errorMessage: "Mock sync error for lifecycle display.",
    createdAt: "2026-06-10T09:00:00.000Z",
    updatedAt: "2026-06-29T07:30:00.000Z",
  },
];

export const mockAccounts: Account[] = [
  {
    id: "acct_amex_card",
    userId,
    providerConnectionId: "conn_amex",
    providerAccountId: "amex_card_001",
    institutionName: "American Express",
    institutionId: "amex",
    name: "Amex Preferred Rewards",
    officialName: "American Express Preferred Rewards Credit Card",
    type: "credit_card",
    subtype: "charge_card",
    currency: "GBP",
    balance: -640,
    availableBalance: 4360,
    creditLimit: 5000,
    mask: "3005",
    purpose: "credit_card",
    accountRole: "credit",
    includeInCashflow: true,
    includeInNetWorth: true,
    includeInSafeToSpend: false,
    isSpendingAccount: false,
    isBillsAccount: false,
    isSavingsAccount: false,
    linkedGoalIds: [],
    syncStatus: "connected",
    lastSyncedAt: createdAt,
    consentExpiresAt: "2026-09-01T09:00:00.000Z",
    notes: "Amex behaves as a credit card liability by default.",
    provider: "mock",
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "acct_nationwide_current",
    userId,
    providerConnectionId: "conn_nationwide",
    providerAccountId: "nw_current_001",
    institutionName: "Nationwide",
    institutionId: "nationwide",
    name: "FlexDirect",
    officialName: "Nationwide FlexDirect Current Account",
    type: "current_account",
    subtype: "current",
    currency: "GBP",
    balance: 3420.7,
    availableBalance: 3420.7,
    creditLimit: null,
    mask: "1122",
    purpose: "main_current_account",
    accountRole: "spending",
    includeInCashflow: true,
    includeInNetWorth: true,
    includeInSafeToSpend: true,
    isSpendingAccount: true,
    isBillsAccount: false,
    isSavingsAccount: false,
    linkedGoalIds: [],
    syncStatus: "syncing",
    lastSyncedAt: "2026-06-30T08:58:00.000Z",
    consentExpiresAt: "2026-09-01T09:00:00.000Z",
    notes: "Primary current account for salary and everyday bills setup.",
    provider: "mock",
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "acct_nationwide_bills",
    userId,
    providerConnectionId: "conn_nationwide",
    providerAccountId: "nw_bills_001",
    institutionName: "Nationwide",
    institutionId: "nationwide",
    name: "Bills pot",
    officialName: "Nationwide FlexDirect Bills Account",
    type: "current_account",
    subtype: "current",
    currency: "GBP",
    balance: 900,
    availableBalance: 900,
    creditLimit: null,
    mask: "2211",
    purpose: "bills_account",
    accountRole: "bills",
    includeInCashflow: true,
    includeInNetWorth: true,
    includeInSafeToSpend: false,
    isSpendingAccount: false,
    isBillsAccount: true,
    isSavingsAccount: false,
    linkedGoalIds: [],
    syncStatus: "syncing",
    lastSyncedAt: "2026-06-30T08:58:00.000Z",
    consentExpiresAt: "2026-09-01T09:00:00.000Z",
    notes: "Ringfenced for Direct Debit and standing order commitments.",
    provider: "mock",
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "acct_nationwide_emergency",
    userId,
    providerConnectionId: "conn_nationwide",
    providerAccountId: "nw_savings_001",
    institutionName: "Nationwide",
    institutionId: "nationwide",
    name: "Emergency fund",
    officialName: "Nationwide Instant Access Saver",
    type: "savings",
    subtype: "savings",
    currency: "GBP",
    balance: 2140,
    availableBalance: 2140,
    creditLimit: null,
    mask: "7788",
    purpose: "emergency_fund",
    accountRole: "savings",
    includeInCashflow: false,
    includeInNetWorth: true,
    includeInSafeToSpend: false,
    isSpendingAccount: false,
    isBillsAccount: false,
    isSavingsAccount: true,
    linkedGoalIds: ["goal_emergency_fund"],
    syncStatus: "syncing",
    lastSyncedAt: "2026-06-30T08:58:00.000Z",
    consentExpiresAt: "2026-09-01T09:00:00.000Z",
    notes: "Ringfenced savings excluded from safe-to-spend.",
    provider: "mock",
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "acct_revolut_everyday",
    userId,
    providerConnectionId: "conn_revolut",
    providerAccountId: "revolut_current_001",
    institutionName: "Revolut",
    institutionId: "revolut",
    name: "Revolut Everyday",
    officialName: "Revolut Current Account",
    type: "current_account",
    subtype: "current",
    currency: "GBP",
    balance: 485,
    availableBalance: 485,
    creditLimit: null,
    mask: "4400",
    purpose: "everyday_spending",
    accountRole: "spending",
    includeInCashflow: true,
    includeInNetWorth: true,
    includeInSafeToSpend: true,
    isSpendingAccount: true,
    isBillsAccount: false,
    isSavingsAccount: false,
    linkedGoalIds: [],
    syncStatus: "needs_reconsent",
    lastSyncedAt: "2026-06-20T08:45:00.000Z",
    consentExpiresAt: "2026-06-20T09:00:00.000Z",
    notes: "Everyday spending account included in safe-to-spend.",
    provider: "mock",
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "acct_revolut_holiday",
    userId,
    providerConnectionId: "conn_revolut",
    providerAccountId: "revolut_holiday_001",
    institutionName: "Revolut",
    institutionId: "revolut",
    name: "Holiday vault",
    officialName: "Revolut Holiday Vault",
    type: "savings",
    subtype: "vault",
    currency: "GBP",
    balance: 520,
    availableBalance: 520,
    creditLimit: null,
    mask: "8800",
    purpose: "holiday_fund",
    accountRole: "savings",
    includeInCashflow: false,
    includeInNetWorth: true,
    includeInSafeToSpend: false,
    isSpendingAccount: false,
    isBillsAccount: false,
    isSavingsAccount: true,
    linkedGoalIds: ["goal_holiday"],
    syncStatus: "needs_reconsent",
    lastSyncedAt: "2026-06-20T08:45:00.000Z",
    consentExpiresAt: "2026-06-20T09:00:00.000Z",
    notes: "Vault-style balance represented as savings by the mock provider.",
    provider: "mock",
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "acct_manual_isa",
    userId,
    providerConnectionId: null,
    providerAccountId: null,
    institutionName: "Manual",
    institutionId: "manual",
    name: "Stocks & Shares ISA estimate",
    officialName: "Manual ISA estimate",
    type: "isa",
    subtype: "isa",
    currency: "GBP",
    balance: 2500,
    availableBalance: null,
    creditLimit: null,
    mask: null,
    purpose: "investment",
    accountRole: "investment",
    includeInCashflow: false,
    includeInNetWorth: true,
    includeInSafeToSpend: false,
    isSpendingAccount: false,
    isBillsAccount: false,
    isSavingsAccount: true,
    linkedGoalIds: [],
    syncStatus: "not_connected",
    lastSyncedAt: null,
    consentExpiresAt: null,
    notes: "Manual estimate until a future provider can see this balance.",
    provider: "manual",
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
];

export const mockCategories: Category[] = [
  {
    id: "cat_income",
    userId,
    name: "Income",
    parentId: null,
    kind: "income",
    budgetType: "income",
    includeInBudget: false,
    status: "active",
  },
  {
    id: "cat_groceries",
    userId,
    name: "Groceries",
    parentId: null,
    kind: "expense",
    budgetType: "essential",
    includeInBudget: true,
    status: "active",
  },
  {
    id: "cat_eating_out",
    userId,
    name: "Eating out",
    parentId: null,
    kind: "expense",
    budgetType: "flexible",
    includeInBudget: true,
    status: "active",
  },
  {
    id: "cat_transport",
    userId,
    name: "Transport",
    parentId: null,
    kind: "expense",
    budgetType: "essential",
    includeInBudget: true,
    status: "active",
  },
  {
    id: "cat_home_bills",
    userId,
    name: "Home bills",
    parentId: null,
    kind: "expense",
    budgetType: "essential",
    includeInBudget: true,
    status: "active",
  },
  {
    id: "cat_personal",
    userId,
    name: "Personal",
    parentId: null,
    kind: "expense",
    budgetType: "flexible",
    includeInBudget: true,
    status: "active",
  },
  {
    id: "cat_savings",
    userId,
    name: "Savings",
    parentId: null,
    kind: "transfer",
    budgetType: "savings",
    includeInBudget: false,
    status: "active",
  },
  {
    id: "cat_debt",
    userId,
    name: "Debt payments",
    parentId: null,
    kind: "expense",
    budgetType: "debt",
    includeInBudget: false,
    status: "active",
  },
];

export const mockBudgetPeriods: BudgetPeriod[] = [
  {
    id: "period_2026_06",
    userId,
    label: "June 2026",
    startDate: "2026-06-01",
    endDate: "2026-06-30",
    status: "open",
  },
  {
    id: "period_2026_07",
    userId,
    label: "July 2026",
    startDate: "2026-07-01",
    endDate: "2026-07-31",
    status: "planned",
  },
];

export const mockBudgets: Budget[] = [
  {
    id: "budget_groceries_2026_06",
    userId,
    categoryId: "cat_groceries",
    periodId: "period_2026_06",
    amount: 460,
    currency: "GBP",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "budget_eating_out_2026_06",
    userId,
    categoryId: "cat_eating_out",
    periodId: "period_2026_06",
    amount: 180,
    currency: "GBP",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "budget_transport_2026_06",
    userId,
    categoryId: "cat_transport",
    periodId: "period_2026_06",
    amount: 240,
    currency: "GBP",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "budget_home_bills_2026_06",
    userId,
    categoryId: "cat_home_bills",
    periodId: "period_2026_06",
    amount: 1220,
    currency: "GBP",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "budget_personal_2026_06",
    userId,
    categoryId: "cat_personal",
    periodId: "period_2026_06",
    amount: 260,
    currency: "GBP",
    createdAt,
    updatedAt: createdAt,
  },
];

export const mockTransactionRecords: Transaction[] = [
  {
    id: "txn_001",
    accountId: "acct_nationwide_current",
    categoryId: "cat_groceries",
    date: "2026-06-28",
    merchant: "Northside Grocers",
    description: "Weekly food shop",
    amount: -64.2,
    currency: "GBP",
    kind: "expense",
    status: "reviewed",
    flags: [],
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "txn_002",
    accountId: "acct_amex_card",
    categoryId: "cat_eating_out",
    date: "2026-06-27",
    merchant: "City Lunch Bar",
    description: "Lunch and coffee",
    amount: -18.5,
    currency: "GBP",
    kind: "expense",
    status: "reviewed",
    flags: ["ahead_of_pace"],
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "txn_003",
    accountId: "acct_nationwide_current",
    categoryId: "cat_income",
    date: "2026-06-25",
    merchant: "Monthly Salary",
    description: "Regular income",
    amount: 2850,
    currency: "GBP",
    kind: "income",
    status: "reviewed",
    flags: [],
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "txn_004",
    accountId: "acct_nationwide_bills",
    categoryId: "cat_home_bills",
    date: "2026-06-25",
    merchant: "Local Energy",
    description: "Direct Debit",
    amount: -118,
    currency: "GBP",
    kind: "expense",
    status: "reviewed",
    flags: ["recurring"],
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "txn_005",
    accountId: "acct_revolut_everyday",
    categoryId: "cat_personal",
    date: "2026-06-24",
    merchant: "Online Homeware",
    description: "Household items",
    amount: -42.9,
    currency: "GBP",
    kind: "expense",
    status: "needs_review",
    flags: ["category_suggested"],
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "txn_006",
    accountId: "acct_nationwide_current",
    categoryId: "cat_groceries",
    date: "2026-06-22",
    merchant: "Market Basket",
    description: "Top-up food shop",
    amount: -86.4,
    currency: "GBP",
    kind: "expense",
    status: "reviewed",
    flags: [],
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "txn_007",
    accountId: "acct_revolut_everyday",
    categoryId: "cat_transport",
    date: "2026-06-19",
    merchant: "TfL",
    description: "Travel card top-up",
    amount: -32,
    currency: "GBP",
    kind: "expense",
    status: "reviewed",
    flags: [],
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "txn_008",
    accountId: "acct_nationwide_current",
    categoryId: "cat_income",
    date: "2026-06-18",
    merchant: "Freelance Client",
    description: "One-off side income",
    amount: 450,
    currency: "GBP",
    kind: "income",
    status: "reviewed",
    flags: [],
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "txn_009",
    accountId: "acct_amex_card",
    categoryId: "cat_eating_out",
    date: "2026-06-16",
    merchant: "Neighbourhood Bistro",
    description: "Dinner",
    amount: -54,
    currency: "GBP",
    kind: "expense",
    status: "reviewed",
    flags: ["ahead_of_pace"],
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "txn_010",
    accountId: "acct_nationwide_bills",
    categoryId: "cat_home_bills",
    date: "2026-06-10",
    merchant: "Mock Landlord",
    description: "Rent",
    amount: -950,
    currency: "GBP",
    kind: "expense",
    status: "reviewed",
    flags: ["recurring"],
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "txn_011",
    accountId: "acct_nationwide_bills",
    categoryId: "cat_home_bills",
    date: "2026-06-05",
    merchant: "City Council",
    description: "Council tax",
    amount: -168,
    currency: "GBP",
    kind: "expense",
    status: "reviewed",
    flags: ["recurring"],
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "txn_012",
    accountId: "acct_nationwide_emergency",
    categoryId: "cat_income",
    date: "2026-06-02",
    merchant: "Savings Interest",
    description: "Monthly interest",
    amount: 3.2,
    currency: "GBP",
    kind: "income",
    status: "reviewed",
    flags: [],
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "txn_013",
    accountId: "acct_nationwide_current",
    categoryId: "cat_savings",
    date: "2026-06-26",
    merchant: "Own account transfer",
    description: "Transfer to emergency fund",
    amount: -300,
    currency: "GBP",
    kind: "transfer",
    status: "reviewed",
    flags: ["own_account_transfer"],
    createdAt,
    updatedAt: createdAt,
  },
];

export const mockBills: Bill[] = [
  {
    id: "bill_rent",
    userId,
    name: "Rent",
    amount: 950,
    currency: "GBP",
    dueDate: "2026-07-01",
    recurrence: { frequency: "monthly", interval: 1 },
    categoryId: "cat_home_bills",
    accountId: "acct_nationwide_bills",
    essential: true,
    includeInCashflow: true,
    status: "confirmed",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "bill_council_tax",
    userId,
    name: "Council tax",
    amount: 168,
    currency: "GBP",
    dueDate: "2026-07-05",
    recurrence: { frequency: "monthly", interval: 1 },
    categoryId: "cat_home_bills",
    accountId: "acct_nationwide_bills",
    essential: true,
    includeInCashflow: true,
    status: "confirmed",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "bill_energy",
    userId,
    name: "Energy Direct Debit",
    amount: 118,
    currency: "GBP",
    dueDate: "2026-07-15",
    recurrence: { frequency: "monthly", interval: 1 },
    categoryId: "cat_home_bills",
    accountId: "acct_nationwide_bills",
    essential: true,
    includeInCashflow: true,
    status: "confirmed",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "bill_water",
    userId,
    name: "Water bill",
    amount: 36.5,
    currency: "GBP",
    dueDate: "2026-07-20",
    recurrence: { frequency: "monthly", interval: 1 },
    categoryId: "cat_home_bills",
    accountId: "acct_nationwide_bills",
    essential: true,
    includeInCashflow: true,
    status: "confirmed",
    createdAt,
    updatedAt: createdAt,
  },
];

export const mockSubscriptions: Subscription[] = [
  {
    id: "sub_mobile",
    userId,
    name: "Mobile",
    amount: 28.4,
    currency: "GBP",
    dueDate: "2026-07-08",
    recurrence: { frequency: "monthly", interval: 1 },
    categoryId: "cat_home_bills",
    accountId: "acct_nationwide_bills",
    includeInCashflow: true,
    status: "confirmed",
    reviewDate: null,
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "sub_streaming",
    userId,
    name: "Streaming bundle",
    amount: 18.99,
    currency: "GBP",
    dueDate: "2026-07-09",
    recurrence: { frequency: "monthly", interval: 1 },
    categoryId: "cat_personal",
    accountId: "acct_amex_card",
    includeInCashflow: true,
    status: "pending_review",
    reviewDate: "2026-07-12",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "sub_gym",
    userId,
    name: "Gym membership",
    amount: 34,
    currency: "GBP",
    dueDate: "2026-07-14",
    recurrence: { frequency: "monthly", interval: 1 },
    categoryId: "cat_personal",
    accountId: "acct_amex_card",
    includeInCashflow: true,
    status: "confirmed",
    reviewDate: null,
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "sub_magazine",
    userId,
    name: "Magazine renewal",
    amount: 72,
    currency: "GBP",
    dueDate: "2026-07-21",
    recurrence: { frequency: "annual", interval: 1 },
    categoryId: "cat_personal",
    accountId: "acct_amex_card",
    includeInCashflow: true,
    status: "pending_review",
    reviewDate: "2026-07-10",
    createdAt,
    updatedAt: createdAt,
  },
];

export const mockSavingsGoals: SavingsGoal[] = [
  {
    id: "goal_emergency_fund",
    userId,
    name: "Emergency fund",
    targetAmount: 5000,
    currentAmount: 0,
    currency: "GBP",
    targetDate: "2026-12-31",
    priority: "high",
    monthlyContribution: 410,
    includeInNetWorth: false,
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "goal_holiday",
    userId,
    name: "Holiday pot",
    targetAmount: 1200,
    currentAmount: 0,
    currency: "GBP",
    targetDate: "2026-09-30",
    priority: "medium",
    monthlyContribution: 227,
    includeInNetWorth: false,
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "goal_home_buffer",
    userId,
    name: "Home buffer",
    targetAmount: 900,
    currentAmount: 275,
    currency: "GBP",
    targetDate: "2026-11-30",
    priority: "medium",
    monthlyContribution: 125,
    includeInNetWorth: false,
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
];

export const mockDebts: Debt[] = [
  {
    id: "debt_personal_loan",
    userId,
    name: "Personal loan",
    balance: 3200,
    currency: "GBP",
    apr: 7.4,
    minimumPayment: 160,
    dueDate: "2026-07-18",
    lender: "Mock Loan Provider",
    accountId: null,
    includeInNetWorth: true,
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
];

export const mockManualFinanceItems: ManualFinanceItem[] = [
  {
    id: "manual_cash_tin",
    name: "Cash tin",
    type: "cash",
    direction: "asset",
    amount: 65,
    currency: "GBP",
    dueDate: null,
    recurrence: null,
    apr: null,
    minimumPayment: null,
    counterparty: null,
    includeInCashflow: true,
    includeInNetWorth: true,
    notes: "Small emergency cash float.",
    status: "active",
    reviewDate: "2026-09-30",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "manual_credit_union",
    name: "Credit union savings",
    type: "offline_account",
    direction: "asset",
    amount: 420,
    currency: "GBP",
    dueDate: null,
    recurrence: null,
    apr: null,
    minimumPayment: null,
    counterparty: "Local credit union",
    includeInCashflow: true,
    includeInNetWorth: true,
    notes: "Offline account updated manually.",
    status: "active",
    reviewDate: "2026-08-31",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "manual_pension_estimate",
    name: "Workplace pension estimate",
    type: "pension_estimate",
    direction: "asset",
    amount: 14200,
    currency: "GBP",
    dueDate: null,
    recurrence: null,
    apr: null,
    minimumPayment: null,
    counterparty: "Pension provider",
    includeInCashflow: false,
    includeInNetWorth: true,
    notes: "Manual estimate, not investment advice.",
    status: "active",
    reviewDate: "2026-12-31",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "manual_old_isa",
    name: "Old ISA estimate",
    type: "isa_investment_balance",
    direction: "asset",
    amount: 950,
    currency: "GBP",
    dueDate: null,
    recurrence: null,
    apr: null,
    minimumPayment: null,
    counterparty: "ISA provider",
    includeInCashflow: false,
    includeInNetWorth: true,
    notes: "Manual balance estimate.",
    status: "active",
    reviewDate: "2026-09-30",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "manual_friend_owed",
    name: "Money owed by friend",
    type: "money_owed_to_user",
    direction: "receivable",
    amount: 180,
    currency: "GBP",
    dueDate: "2026-07-30",
    recurrence: { frequency: "one_off", interval: 1 },
    apr: null,
    minimumPayment: null,
    counterparty: "Friend",
    includeInCashflow: true,
    includeInNetWorth: true,
    notes: "Expected repayment after payday.",
    status: "active",
    reviewDate: "2026-07-31",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "manual_sofa_finance",
    name: "Sofa finance",
    type: "debt",
    direction: "liability",
    amount: 480,
    currency: "GBP",
    dueDate: "2026-07-11",
    recurrence: { frequency: "monthly", interval: 1 },
    apr: 0,
    minimumPayment: 60,
    counterparty: "Furniture store",
    includeInCashflow: true,
    includeInNetWorth: true,
    notes: "Interest-free store finance.",
    status: "active",
    reviewDate: "2026-10-31",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "manual_sibling_payable",
    name: "Money owed to sibling",
    type: "money_user_owes",
    direction: "payable",
    amount: 120,
    currency: "GBP",
    dueDate: "2026-07-20",
    recurrence: { frequency: "one_off", interval: 1 },
    apr: null,
    minimumPayment: null,
    counterparty: "Sibling",
    includeInCashflow: true,
    includeInNetWorth: true,
    notes: "Personal repayment planned before payday.",
    status: "active",
    reviewDate: "2026-07-21",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "manual_car_mot",
    name: "Car MOT",
    type: "future_expense",
    direction: "expense",
    amount: 210,
    currency: "GBP",
    dueDate: "2026-07-18",
    recurrence: { frequency: "annual", interval: 1 },
    apr: null,
    minimumPayment: null,
    counterparty: "Local garage",
    includeInCashflow: true,
    includeInNetWorth: false,
    notes: "Estimated one-off future expense.",
    status: "active",
    reviewDate: "2026-07-10",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "manual_window_cleaner",
    name: "Window cleaner",
    type: "manual_bill",
    direction: "expense",
    amount: 24,
    currency: "GBP",
    dueDate: "2026-07-10",
    recurrence: { frequency: "monthly", interval: 1 },
    apr: null,
    minimumPayment: null,
    counterparty: "Window cleaner",
    includeInCashflow: true,
    includeInNetWorth: false,
    notes: "Manual recurring bill.",
    status: "active",
    reviewDate: "2026-09-30",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "manual_salary_forecast",
    name: "Salary forecast",
    type: "manual_income",
    direction: "income",
    amount: 2850,
    currency: "GBP",
    dueDate: "2026-07-25",
    recurrence: { frequency: "monthly", interval: 1 },
    apr: null,
    minimumPayment: null,
    counterparty: "Employer",
    includeInCashflow: true,
    includeInNetWorth: false,
    notes: "Manual recurring income forecast.",
    status: "active",
    reviewDate: "2026-08-25",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "manual_housemate_contribution",
    name: "Housemate contribution",
    type: "manual_income",
    direction: "income",
    amount: 250,
    currency: "GBP",
    dueDate: "2026-07-01",
    recurrence: { frequency: "monthly", interval: 1 },
    apr: null,
    minimumPayment: null,
    counterparty: "Housemate",
    includeInCashflow: true,
    includeInNetWorth: false,
    notes: "Manual recurring income contribution.",
    status: "active",
    reviewDate: "2026-09-30",
    createdAt,
    updatedAt: createdAt,
  },
];

const totalAssets = calculateTotalAssets(mockAccounts, mockManualFinanceItems);
const totalLiabilities = calculateTotalLiabilities(
  mockAccounts,
  mockDebts,
  mockManualFinanceItems,
);

export const mockNetWorthSnapshots: NetWorthSnapshot[] = [
  {
    id: "nws_2026_06_30",
    userId,
    date: "2026-06-30",
    assetsTotal: totalAssets,
    liabilitiesTotal: totalLiabilities,
    netWorth: totalAssets - totalLiabilities,
    currency: "GBP",
    createdAt,
  },
];

export const mockAIInsights: AIInsight[] = [
  {
    id: "insight_weekly_001",
    userId,
    type: "weekly_review",
    title: "Flexible spending needs a light review",
    summary:
      "Safe-to-spend remains positive after upcoming bills, goal contributions, debt payments, and the minimum buffer.",
    evidence: [
      "Manual bills and future expenses are included in the cashflow view.",
      "Eating out has two flagged transactions in the current period.",
    ],
    assumptions: ["All figures are mock seed data.", "No Open Banking data is connected."],
    nextAction: "Review flexible spending before changing any budget.",
    status: "active",
    createdAt,
  },
];

export const mockAlerts: Alert[] = [
  {
    id: "alert_budget_eating_out",
    userId,
    type: "budget_pace_high",
    severity: "warning",
    title: "Eating out is ahead of pace",
    message: "Two recent transactions are pushing flexible spending higher than planned.",
    entityType: "category",
    entityId: "cat_eating_out",
    status: "new",
    createdAt,
  },
  {
    id: "alert_subscription_review",
    userId,
    type: "subscription_review",
    severity: "info",
    title: "Streaming bundle needs review",
    message: "The next payment is marked for review before becoming a confirmed subscription.",
    entityType: "subscription",
    entityId: "sub_streaming",
    status: "new",
    createdAt,
  },
];

export const mockNotificationPreferences: NotificationPreference[] =
  createDefaultNotificationPreferences(userId, createdAt);

export const mockNotificationRules: NotificationRule[] = [
  {
    id: "rule_low_balance",
    userId,
    type: "low_balance",
    enabled: true,
    thresholdAmount: 250,
    thresholdPercentage: null,
    daysBefore: null,
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "rule_budget_threshold",
    userId,
    type: "budget_threshold",
    enabled: true,
    thresholdAmount: null,
    thresholdPercentage: 0.85,
    daysBefore: null,
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "rule_bill_due",
    userId,
    type: "bill_due",
    enabled: true,
    thresholdAmount: null,
    thresholdPercentage: null,
    daysBefore: 7,
    createdAt,
    updatedAt: createdAt,
  },
];

export const mockPushSubscriptionRecords: PushSubscriptionRecord[] = [
  {
    id: "push_placeholder_001",
    userId,
    endpointHash: "mock-endpoint-hash",
    browser: "iPhone Safari placeholder",
    permission: "default",
    status: "placeholder",
    lastSeenAt: createdAt,
    createdAt,
    updatedAt: createdAt,
  },
];

export const mockFinanceData = {
  userProfile: mockUserProfile,
  accounts: mockAccounts,
  transactions: mockTransactionRecords,
  categories: mockCategories,
  budgets: mockBudgets,
  budgetPeriods: mockBudgetPeriods,
  bills: mockBills,
  subscriptions: mockSubscriptions,
  savingsGoals: mockSavingsGoals,
  debts: mockDebts,
  netWorthSnapshots: mockNetWorthSnapshots,
  aiInsights: mockAIInsights,
  alerts: mockAlerts,
  notificationPreferences: mockNotificationPreferences,
  notificationRules: mockNotificationRules,
  pushSubscriptionRecords: mockPushSubscriptionRecords,
  bankConnections: mockBankConnections,
  manualFinanceItems: mockManualFinanceItems,
};

const currentPeriod = mockBudgetPeriods[0];
const projectionPeriod = mockBudgetPeriods[1];
const asOfDate = "2026-06-30";
const nextPaydayDate = "2026-07-25";
const elapsedBudgetPeriodRatio = 1;

const plannedSavingsBeforePayday = mockSavingsGoals.reduce(
  (total, goal) => total + goal.monthlyContribution,
  0,
);

const currentCash = calculateTotalCurrentCash(mockAccounts, mockManualFinanceItems);
const safeToSpendEligibleCash = calculateSafeToSpendEligibleCash(mockAccounts);
const billsAccountBalance = calculateBillsAccountBalance(mockAccounts);
const cashflowAccountBalance = calculateCashflowAccountBalance(mockAccounts);
const billsDueBeforePayday = calculateBillsDueBeforePayday(
  mockBills,
  mockSubscriptions,
  mockManualFinanceItems,
  asOfDate,
  nextPaydayDate,
);
const debtPaymentsBeforePayday = calculateDebtPaymentsDueBeforePayday(
  mockDebts,
  mockManualFinanceItems,
  asOfDate,
  nextPaydayDate,
);
const projectionIncome = calculateMonthlyIncome(
  mockTransactionRecords,
  mockManualFinanceItems,
  projectionPeriod,
);
const projectionOutflows =
  calculateBillsDueBeforePayday(
    mockBills,
    mockSubscriptions,
    mockManualFinanceItems,
    projectionPeriod.startDate,
    projectionPeriod.endDate,
  ) +
  calculateDebtPaymentsDueBeforePayday(
    mockDebts,
    mockManualFinanceItems,
    projectionPeriod.startDate,
    projectionPeriod.endDate,
  ) +
  plannedSavingsBeforePayday +
  920;

export const dashboardSummary = {
  currentCash,
  safeToSpend: calculateSafeToSpendAmount({
    currentCash: safeToSpendEligibleCash,
    billsDueBeforePayday,
    plannedSavingsBeforePayday,
    debtPaymentsBeforePayday,
    minimumBuffer: mockUserProfile.minimumBuffer,
    reservedGoalContributions: 0,
  }),
  billsDueBeforePayday,
  monthlyIncome: calculateMonthlyIncome(
    mockTransactionRecords,
    mockManualFinanceItems,
    currentPeriod,
  ),
  monthlySpending: calculateMonthlySpending(
    mockTransactionRecords,
    mockManualFinanceItems,
    currentPeriod,
  ),
  projectedMonthEndBalance: calculateProjectedMonthEndBalance({
    currentCash,
    expectedIncome: projectionIncome,
    plannedOutflows: projectionOutflows,
  }),
  totalAssets,
  totalLiabilities,
  netWorth: calculateNetWorth(mockAccounts, mockDebts, mockManualFinanceItems),
  debtSummary: calculateDebtSummary(mockDebts, mockManualFinanceItems, mockAccounts),
  safeToSpendEligibleCash,
  billsAccountBalance,
  cashflowAccountBalance,
  nextPayday: formatDateShort(nextPaydayDate),
  budgetStatus: "Mostly on track",
};

export const budgetHealth = calculateBudgetHealth(
  mockBudgets,
  mockTransactionRecords,
  mockCategories,
  currentPeriod,
  elapsedBudgetPeriodRatio,
);

export const mockAppNotifications: AppNotification[] = generateFinanceNotifications({
  userId,
  asOfDate,
  safeToSpend: dashboardSummary.safeToSpend,
  previousSafeToSpend: dashboardSummary.safeToSpend + 145,
  preferences: mockNotificationPreferences,
  bills: mockBills,
  budgetHealth,
  bankConnections: mockBankConnections,
  manualFinanceItems: mockManualFinanceItems,
});

export const upcomingBills = getUpcomingBillItems(
  mockBills,
  mockSubscriptions,
  mockManualFinanceItems,
  asOfDate,
  nextPaydayDate,
).map((item) => ({
  ...item,
  dueDateLabel: formatDateShort(item.dueDate),
}));

export const upcomingManualCashflowItems = getUpcomingManualCashflowItems(
  mockManualFinanceItems,
  asOfDate,
  projectionPeriod.endDate,
);

function categoryName(categoryId: string) {
  return mockCategories.find((category) => category.id === categoryId)?.name ?? "Other";
}

function accountName(accountId: string) {
  return mockAccounts.find((account) => account.id === accountId)?.name ?? "Mock account";
}

function transactionTone(transaction: Transaction): Tone {
  if (transaction.status === "needs_review") {
    return "warning";
  }

  if (transaction.flags.includes("ahead_of_pace")) {
    return "warning";
  }

  if (transaction.flags.includes("recurring")) {
    return "neutral";
  }

  return "good";
}

function transactionStatusLabel(transaction: Transaction) {
  if (transaction.status === "needs_review") {
    return "Needs review";
  }

  if (transaction.flags.includes("ahead_of_pace")) {
    return "Ahead of pace";
  }

  if (transaction.flags.includes("recurring")) {
    return "Recurring";
  }

  return "Reviewed";
}

export const mockTransactions = mockTransactionRecords.map((transaction) => ({
  id: transaction.id,
  date: formatDateShort(transaction.date),
  account: accountName(transaction.accountId),
  merchant: transaction.merchant,
  description: transaction.description,
  amount: transaction.amount,
  category: categoryName(transaction.categoryId),
  status: transactionStatusLabel(transaction),
  tone: transactionTone(transaction),
}));

export const recurringPayments = [
  ...mockBills.map((bill) => ({
    id: bill.id,
    name: bill.name,
    type: bill.essential ? "Essential bill" : "Bill",
    cadence: bill.recurrence.frequency,
    nextDue: formatDateShort(bill.dueDate),
    amount: bill.amount,
    status: "Confirmed",
    tone: "good" as const,
  })),
  ...mockSubscriptions.map((subscription) => ({
    id: subscription.id,
    name: subscription.name,
    type: "Subscription",
    cadence: subscription.recurrence.frequency,
    nextDue: formatDateShort(subscription.dueDate),
    amount: subscription.amount,
    status: subscription.status === "pending_review" ? "Needs review" : "Confirmed",
    tone: subscription.status === "pending_review" ? ("warning" as const) : ("neutral" as const),
  })),
  ...mockManualFinanceItems
    .filter((item) => item.type === "manual_bill" || item.type === "future_expense")
    .map((item) => ({
      id: item.id,
      name: item.name,
      type: item.type === "manual_bill" ? "Manual bill" : "Future expense",
      cadence: item.recurrence?.frequency ?? "one_off",
      nextDue: item.dueDate ? formatDateShort(item.dueDate) : "No date",
      amount: item.amount,
      status: "Manual",
      tone: "neutral" as const,
    })),
];

export const recurringPaymentSummary = {
  confirmedBills: mockBills.filter((bill) => bill.status === "confirmed").length,
  subscriptions: mockSubscriptions.length,
  needsReview: [
    ...mockSubscriptions.filter((subscription) => subscription.status === "pending_review"),
    ...mockManualFinanceItems.filter((item) => item.status === "pending_review"),
  ].length,
};

export const savingsGoals = mockSavingsGoals.map((goal) => ({
  ...goal,
  currentAmount: goal.currentAmount + calculateLinkedSavingsGoalBalance(mockAccounts, goal.id),
  targetDate: formatDateShort(goal.targetDate),
  priority: `${goal.priority[0].toUpperCase()}${goal.priority.slice(1)}`,
  suggestedMonthlyContribution: goal.monthlyContribution,
  linkedAccountBalance: calculateLinkedSavingsGoalBalance(mockAccounts, goal.id),
  progress: calculateSavingsGoalProgress(
    goal,
    calculateLinkedSavingsGoalBalance(mockAccounts, goal.id),
  ),
}));

export const dashboardInsight = mockAIInsights[0];

export const connectedAccounts = mockAccounts.map((account) => ({
  ...account,
  displaySyncStatus: account.providerConnectionId
    ? getConnectionLifecycleStatus(
        mockBankConnections.find(
          (connection) => connection.id === account.providerConnectionId,
        ) ?? mockBankConnections[0],
        asOfDate,
      )
    : account.syncStatus,
  billsPaid: [...mockBills, ...mockSubscriptions].filter(
    (item) => item.accountId === account.id,
  ),
  linkedGoals: mockSavingsGoals.filter((goal) => account.linkedGoalIds.includes(goal.id)),
}));

export const connectedAccountSummary = {
  connectedInstitutions: mockBankConnections.filter(
    (connection) =>
      getConnectionLifecycleStatus(connection, asOfDate) === "connected" ||
      getConnectionLifecycleStatus(connection, asOfDate) === "syncing",
  ).length,
  needsReconsent: mockBankConnections.filter(
    (connection) => getConnectionLifecycleStatus(connection, asOfDate) === "needs_reconsent",
  ).length,
  syncFailed: mockBankConnections.filter(
    (connection) => getConnectionLifecycleStatus(connection, asOfDate) === "sync_failed",
  ).length,
};

export const connectionLifecycleStates = [
  "not_connected",
  "connecting",
  "connected",
  "needs_reconsent",
  "syncing",
  "sync_failed",
  "disconnected",
] as const;

export const bankConnectionsWithDisplayStatus = mockBankConnections.map((connection) => ({
  ...connection,
  displayStatus: getConnectionLifecycleStatus(connection, asOfDate),
}));

// ---------------------------------------------------------------------------
// v2 finance engine mock data (synthetic, GBP, no real financial data).
// Exercises payday planning, overdraft escape, debt freedom and savings phases.
// ---------------------------------------------------------------------------

export const mockPaydayPlans: PaydayPlan[] = [
  {
    id: "payday_plan_primary",
    userId,
    monthlyIncome: 2600,
    paydayDate: "2026-07-25",
    preferredBuffer: 350,
    billsAccountTarget: 1100,
    minimumDebtPaymentsTarget: 320,
    overdraftReductionTarget: 150,
    essentialSpendingTarget: 500,
    emergencyBufferTarget: 100,
    savingsTarget: 200,
    flexibleSpendingTarget: 230,
    createdAt,
    updatedAt: createdAt,
  },
];

export const mockPaydayPlan = mockPaydayPlans[0];

export const mockOverdraftPlans: OverdraftPlan[] = [
  {
    id: "overdraft_plan_flexdirect",
    userId,
    linkedAccountId: "acct_nationwide_current",
    overdraftLimit: 1000,
    currentOverdraftUsed: 600,
    targetReductionPerPayday: 150,
    feesOrInterest: 18.9,
    targetOverdraftFreeDate: "2026-12-25",
    projectedOverdraftFreeDate: null,
    riskBeforePayday: "medium",
    recommendedPaydayAction:
      "Reduce the overdraft by at least £150.00 this payday.",
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
];

export const mockOverdraftPlan = mockOverdraftPlans[0];

/**
 * Synthetic debts with distinct balances, APRs and custom priorities so debt
 * strategy ordering (snowball / avalanche / custom) is unambiguous in tests.
 * Kept separate from {@link mockDebts} so existing finance fixtures are stable.
 */
export const mockStrategyDebts: Debt[] = [
  {
    id: "debt_store_card",
    userId,
    name: "Store card",
    balance: 450,
    currency: "GBP",
    apr: 12.0,
    minimumPayment: 25,
    dueDate: "2026-07-12",
    lender: "Mock Store Finance",
    accountId: null,
    includeInNetWorth: true,
    priority: 2,
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "debt_credit_card",
    userId,
    name: "Credit card",
    balance: 2100,
    currency: "GBP",
    apr: 21.9,
    minimumPayment: 75,
    dueDate: "2026-07-20",
    lender: "Mock Bank Cards",
    accountId: null,
    includeInNetWorth: true,
    priority: 3,
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "debt_car_finance",
    userId,
    name: "Car finance",
    balance: 5200,
    currency: "GBP",
    apr: 9.4,
    minimumPayment: 210,
    dueDate: "2026-07-28",
    lender: "Mock Motor Finance",
    accountId: null,
    includeInNetWorth: true,
    priority: 1,
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
];
