import type {
  Account,
  AIInsight,
  Alert,
  Bill,
  Budget,
  BudgetPeriod,
  Category,
  Debt,
  ManualFinanceItem,
  NetWorthSnapshot,
  SavingsGoal,
  Subscription,
  Transaction,
  UserProfile,
} from "@/lib/domain";
import {
  calculateBillsDueBeforePayday,
  calculateBudgetHealth,
  calculateDebtPaymentsDueBeforePayday,
  calculateDebtSummary,
  calculateMonthlyIncome,
  calculateMonthlySpending,
  calculateNetWorth,
  calculateProjectedMonthEndBalance,
  calculateSafeToSpendAmount,
  calculateSavingsGoalProgress,
  calculateTotalAssets,
  calculateTotalCurrentCash,
  calculateTotalLiabilities,
  getUpcomingBillItems,
  getUpcomingManualCashflowItems,
  type BudgetHealthItem,
  type Tone,
} from "@/lib/finance";
import { formatDateShort } from "@/lib/format";

export type BudgetCategory = BudgetHealthItem;

const userId = "user_mock_001";
const createdAt = "2026-06-30T09:00:00.000Z";

export const mockUserProfile: UserProfile = {
  id: userId,
  displayName: "Demo User",
  locale: "en-GB",
  currency: "GBP",
  paydayDayOfMonth: 25,
  minimumBuffer: 350,
  createdAt,
  updatedAt: createdAt,
};

export const mockAccounts: Account[] = [
  {
    id: "acct_current",
    userId,
    name: "Mock current account",
    type: "current_account",
    currency: "GBP",
    balance: 2420.7,
    includeInCash: true,
    includeInNetWorth: true,
    provider: "mock",
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "acct_easy_access_savings",
    userId,
    name: "Easy access savings",
    type: "savings",
    currency: "GBP",
    balance: 1000,
    includeInCash: true,
    includeInNetWorth: true,
    provider: "mock",
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "acct_credit_card",
    userId,
    name: "Mock credit card",
    type: "credit_card",
    currency: "GBP",
    balance: -640,
    includeInCash: false,
    includeInNetWorth: true,
    provider: "mock",
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "acct_stocks_isa",
    userId,
    name: "Stocks & Shares ISA estimate",
    type: "isa",
    currency: "GBP",
    balance: 2500,
    includeInCash: false,
    includeInNetWorth: true,
    provider: "manual",
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
];

export const mockCategories: Category[] = [
  {
    id: "cat_income",
    userId,
    name: "Income",
    parentId: null,
    kind: "income",
    budgetType: "income",
    includeInBudget: false,
    status: "active",
  },
  {
    id: "cat_groceries",
    userId,
    name: "Groceries",
    parentId: null,
    kind: "expense",
    budgetType: "essential",
    includeInBudget: true,
    status: "active",
  },
  {
    id: "cat_eating_out",
    userId,
    name: "Eating out",
    parentId: null,
    kind: "expense",
    budgetType: "flexible",
    includeInBudget: true,
    status: "active",
  },
  {
    id: "cat_transport",
    userId,
    name: "Transport",
    parentId: null,
    kind: "expense",
    budgetType: "essential",
    includeInBudget: true,
    status: "active",
  },
  {
    id: "cat_home_bills",
    userId,
    name: "Home bills",
    parentId: null,
    kind: "expense",
    budgetType: "essential",
    includeInBudget: true,
    status: "active",
  },
  {
    id: "cat_personal",
    userId,
    name: "Personal",
    parentId: null,
    kind: "expense",
    budgetType: "flexible",
    includeInBudget: true,
    status: "active",
  },
  {
    id: "cat_savings",
    userId,
    name: "Savings",
    parentId: null,
    kind: "transfer",
    budgetType: "savings",
    includeInBudget: false,
    status: "active",
  },
  {
    id: "cat_debt",
    userId,
    name: "Debt payments",
    parentId: null,
    kind: "expense",
    budgetType: "debt",
    includeInBudget: false,
    status: "active",
  },
];

export const mockBudgetPeriods: BudgetPeriod[] = [
  {
    id: "period_2026_06",
    userId,
    label: "June 2026",
    startDate: "2026-06-01",
    endDate: "2026-06-30",
    status: "open",
  },
  {
    id: "period_2026_07",
    userId,
    label: "July 2026",
    startDate: "2026-07-01",
    endDate: "2026-07-31",
    status: "planned",
  },
];

export const mockBudgets: Budget[] = [
  {
    id: "budget_groceries_2026_06",
    userId,
    categoryId: "cat_groceries",
    periodId: "period_2026_06",
    amount: 460,
    currency: "GBP",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "budget_eating_out_2026_06",
    userId,
    categoryId: "cat_eating_out",
    periodId: "period_2026_06",
    amount: 180,
    currency: "GBP",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "budget_transport_2026_06",
    userId,
    categoryId: "cat_transport",
    periodId: "period_2026_06",
    amount: 240,
    currency: "GBP",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "budget_home_bills_2026_06",
    userId,
    categoryId: "cat_home_bills",
    periodId: "period_2026_06",
    amount: 1220,
    currency: "GBP",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "budget_personal_2026_06",
    userId,
    categoryId: "cat_personal",
    periodId: "period_2026_06",
    amount: 260,
    currency: "GBP",
    createdAt,
    updatedAt: createdAt,
  },
];

export const mockTransactionRecords: Transaction[] = [
  {
    id: "txn_001",
    accountId: "acct_current",
    categoryId: "cat_groceries",
    date: "2026-06-28",
    merchant: "Northside Grocers",
    description: "Weekly food shop",
    amount: -64.2,
    currency: "GBP",
    kind: "expense",
    status: "reviewed",
    flags: [],
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "txn_002",
    accountId: "acct_credit_card",
    categoryId: "cat_eating_out",
    date: "2026-06-27",
    merchant: "City Lunch Bar",
    description: "Lunch and coffee",
    amount: -18.5,
    currency: "GBP",
    kind: "expense",
    status: "reviewed",
    flags: ["ahead_of_pace"],
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "txn_003",
    accountId: "acct_current",
    categoryId: "cat_income",
    date: "2026-06-25",
    merchant: "Monthly Salary",
    description: "Regular income",
    amount: 2850,
    currency: "GBP",
    kind: "income",
    status: "reviewed",
    flags: [],
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "txn_004",
    accountId: "acct_current",
    categoryId: "cat_home_bills",
    date: "2026-06-25",
    merchant: "Local Energy",
    description: "Direct Debit",
    amount: -118,
    currency: "GBP",
    kind: "expense",
    status: "reviewed",
    flags: ["recurring"],
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "txn_005",
    accountId: "acct_credit_card",
    categoryId: "cat_personal",
    date: "2026-06-24",
    merchant: "Online Homeware",
    description: "Household items",
    amount: -42.9,
    currency: "GBP",
    kind: "expense",
    status: "needs_review",
    flags: ["category_suggested"],
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "txn_006",
    accountId: "acct_current",
    categoryId: "cat_groceries",
    date: "2026-06-22",
    merchant: "Market Basket",
    description: "Top-up food shop",
    amount: -86.4,
    currency: "GBP",
    kind: "expense",
    status: "reviewed",
    flags: [],
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "txn_007",
    accountId: "acct_current",
    categoryId: "cat_transport",
    date: "2026-06-19",
    merchant: "TfL",
    description: "Travel card top-up",
    amount: -32,
    currency: "GBP",
    kind: "expense",
    status: "reviewed",
    flags: [],
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "txn_008",
    accountId: "acct_current",
    categoryId: "cat_income",
    date: "2026-06-18",
    merchant: "Freelance Client",
    description: "One-off side income",
    amount: 450,
    currency: "GBP",
    kind: "income",
    status: "reviewed",
    flags: [],
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "txn_009",
    accountId: "acct_credit_card",
    categoryId: "cat_eating_out",
    date: "2026-06-16",
    merchant: "Neighbourhood Bistro",
    description: "Dinner",
    amount: -54,
    currency: "GBP",
    kind: "expense",
    status: "reviewed",
    flags: ["ahead_of_pace"],
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "txn_010",
    accountId: "acct_current",
    categoryId: "cat_home_bills",
    date: "2026-06-10",
    merchant: "Mock Landlord",
    description: "Rent",
    amount: -950,
    currency: "GBP",
    kind: "expense",
    status: "reviewed",
    flags: ["recurring"],
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "txn_011",
    accountId: "acct_current",
    categoryId: "cat_home_bills",
    date: "2026-06-05",
    merchant: "City Council",
    description: "Council tax",
    amount: -168,
    currency: "GBP",
    kind: "expense",
    status: "reviewed",
    flags: ["recurring"],
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "txn_012",
    accountId: "acct_easy_access_savings",
    categoryId: "cat_income",
    date: "2026-06-02",
    merchant: "Savings Interest",
    description: "Monthly interest",
    amount: 3.2,
    currency: "GBP",
    kind: "income",
    status: "reviewed",
    flags: [],
    createdAt,
    updatedAt: createdAt,
  },
];

export const mockBills: Bill[] = [
  {
    id: "bill_rent",
    userId,
    name: "Rent",
    amount: 950,
    currency: "GBP",
    dueDate: "2026-07-01",
    recurrence: { frequency: "monthly", interval: 1 },
    categoryId: "cat_home_bills",
    accountId: "acct_current",
    essential: true,
    includeInCashflow: true,
    status: "confirmed",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "bill_council_tax",
    userId,
    name: "Council tax",
    amount: 168,
    currency: "GBP",
    dueDate: "2026-07-05",
    recurrence: { frequency: "monthly", interval: 1 },
    categoryId: "cat_home_bills",
    accountId: "acct_current",
    essential: true,
    includeInCashflow: true,
    status: "confirmed",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "bill_energy",
    userId,
    name: "Energy Direct Debit",
    amount: 118,
    currency: "GBP",
    dueDate: "2026-07-15",
    recurrence: { frequency: "monthly", interval: 1 },
    categoryId: "cat_home_bills",
    accountId: "acct_current",
    essential: true,
    includeInCashflow: true,
    status: "confirmed",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "bill_water",
    userId,
    name: "Water bill",
    amount: 36.5,
    currency: "GBP",
    dueDate: "2026-07-20",
    recurrence: { frequency: "monthly", interval: 1 },
    categoryId: "cat_home_bills",
    accountId: "acct_current",
    essential: true,
    includeInCashflow: true,
    status: "confirmed",
    createdAt,
    updatedAt: createdAt,
  },
];

export const mockSubscriptions: Subscription[] = [
  {
    id: "sub_mobile",
    userId,
    name: "Mobile",
    amount: 28.4,
    currency: "GBP",
    dueDate: "2026-07-08",
    recurrence: { frequency: "monthly", interval: 1 },
    categoryId: "cat_home_bills",
    accountId: "acct_current",
    includeInCashflow: true,
    status: "confirmed",
    reviewDate: null,
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "sub_streaming",
    userId,
    name: "Streaming bundle",
    amount: 18.99,
    currency: "GBP",
    dueDate: "2026-07-09",
    recurrence: { frequency: "monthly", interval: 1 },
    categoryId: "cat_personal",
    accountId: "acct_credit_card",
    includeInCashflow: true,
    status: "pending_review",
    reviewDate: "2026-07-12",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "sub_gym",
    userId,
    name: "Gym membership",
    amount: 34,
    currency: "GBP",
    dueDate: "2026-07-14",
    recurrence: { frequency: "monthly", interval: 1 },
    categoryId: "cat_personal",
    accountId: "acct_credit_card",
    includeInCashflow: true,
    status: "confirmed",
    reviewDate: null,
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "sub_magazine",
    userId,
    name: "Magazine renewal",
    amount: 72,
    currency: "GBP",
    dueDate: "2026-07-21",
    recurrence: { frequency: "annual", interval: 1 },
    categoryId: "cat_personal",
    accountId: "acct_credit_card",
    includeInCashflow: true,
    status: "pending_review",
    reviewDate: "2026-07-10",
    createdAt,
    updatedAt: createdAt,
  },
];

export const mockSavingsGoals: SavingsGoal[] = [
  {
    id: "goal_emergency_fund",
    userId,
    name: "Emergency fund",
    targetAmount: 5000,
    currentAmount: 2140,
    currency: "GBP",
    targetDate: "2026-12-31",
    priority: "high",
    monthlyContribution: 410,
    includeInNetWorth: false,
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "goal_holiday",
    userId,
    name: "Holiday pot",
    targetAmount: 1200,
    currentAmount: 520,
    currency: "GBP",
    targetDate: "2026-09-30",
    priority: "medium",
    monthlyContribution: 227,
    includeInNetWorth: false,
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "goal_home_buffer",
    userId,
    name: "Home buffer",
    targetAmount: 900,
    currentAmount: 275,
    currency: "GBP",
    targetDate: "2026-11-30",
    priority: "medium",
    monthlyContribution: 125,
    includeInNetWorth: false,
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
];

export const mockDebts: Debt[] = [
  {
    id: "debt_credit_card",
    userId,
    name: "Mock credit card",
    balance: 640,
    currency: "GBP",
    apr: 22.9,
    minimumPayment: 90,
    dueDate: "2026-07-12",
    lender: "Mock Card Provider",
    accountId: "acct_credit_card",
    includeInNetWorth: true,
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "debt_personal_loan",
    userId,
    name: "Personal loan",
    balance: 3200,
    currency: "GBP",
    apr: 7.4,
    minimumPayment: 160,
    dueDate: "2026-07-18",
    lender: "Mock Loan Provider",
    accountId: null,
    includeInNetWorth: true,
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
];

export const mockManualFinanceItems: ManualFinanceItem[] = [
  {
    id: "manual_cash_tin",
    name: "Cash tin",
    type: "cash",
    direction: "asset",
    amount: 65,
    currency: "GBP",
    dueDate: null,
    recurrence: null,
    apr: null,
    minimumPayment: null,
    counterparty: null,
    includeInCashflow: true,
    includeInNetWorth: true,
    notes: "Small emergency cash float.",
    status: "active",
    reviewDate: "2026-09-30",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "manual_credit_union",
    name: "Credit union savings",
    type: "offline_account",
    direction: "asset",
    amount: 420,
    currency: "GBP",
    dueDate: null,
    recurrence: null,
    apr: null,
    minimumPayment: null,
    counterparty: "Local credit union",
    includeInCashflow: true,
    includeInNetWorth: true,
    notes: "Offline account updated manually.",
    status: "active",
    reviewDate: "2026-08-31",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "manual_pension_estimate",
    name: "Workplace pension estimate",
    type: "pension_estimate",
    direction: "asset",
    amount: 14200,
    currency: "GBP",
    dueDate: null,
    recurrence: null,
    apr: null,
    minimumPayment: null,
    counterparty: "Pension provider",
    includeInCashflow: false,
    includeInNetWorth: true,
    notes: "Manual estimate, not investment advice.",
    status: "active",
    reviewDate: "2026-12-31",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "manual_old_isa",
    name: "Old ISA estimate",
    type: "isa_investment_balance",
    direction: "asset",
    amount: 950,
    currency: "GBP",
    dueDate: null,
    recurrence: null,
    apr: null,
    minimumPayment: null,
    counterparty: "ISA provider",
    includeInCashflow: false,
    includeInNetWorth: true,
    notes: "Manual balance estimate.",
    status: "active",
    reviewDate: "2026-09-30",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "manual_friend_owed",
    name: "Money owed by friend",
    type: "money_owed_to_user",
    direction: "receivable",
    amount: 180,
    currency: "GBP",
    dueDate: "2026-07-30",
    recurrence: { frequency: "one_off", interval: 1 },
    apr: null,
    minimumPayment: null,
    counterparty: "Friend",
    includeInCashflow: true,
    includeInNetWorth: true,
    notes: "Expected repayment after payday.",
    status: "active",
    reviewDate: "2026-07-31",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "manual_sofa_finance",
    name: "Sofa finance",
    type: "debt",
    direction: "liability",
    amount: 480,
    currency: "GBP",
    dueDate: "2026-07-11",
    recurrence: { frequency: "monthly", interval: 1 },
    apr: 0,
    minimumPayment: 60,
    counterparty: "Furniture store",
    includeInCashflow: true,
    includeInNetWorth: true,
    notes: "Interest-free store finance.",
    status: "active",
    reviewDate: "2026-10-31",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "manual_sibling_payable",
    name: "Money owed to sibling",
    type: "money_user_owes",
    direction: "payable",
    amount: 120,
    currency: "GBP",
    dueDate: "2026-07-20",
    recurrence: { frequency: "one_off", interval: 1 },
    apr: null,
    minimumPayment: null,
    counterparty: "Sibling",
    includeInCashflow: true,
    includeInNetWorth: true,
    notes: "Personal repayment planned before payday.",
    status: "active",
    reviewDate: "2026-07-21",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "manual_car_mot",
    name: "Car MOT",
    type: "future_expense",
    direction: "expense",
    amount: 210,
    currency: "GBP",
    dueDate: "2026-07-18",
    recurrence: { frequency: "annual", interval: 1 },
    apr: null,
    minimumPayment: null,
    counterparty: "Local garage",
    includeInCashflow: true,
    includeInNetWorth: false,
    notes: "Estimated one-off future expense.",
    status: "active",
    reviewDate: "2026-07-10",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "manual_window_cleaner",
    name: "Window cleaner",
    type: "manual_bill",
    direction: "expense",
    amount: 24,
    currency: "GBP",
    dueDate: "2026-07-10",
    recurrence: { frequency: "monthly", interval: 1 },
    apr: null,
    minimumPayment: null,
    counterparty: "Window cleaner",
    includeInCashflow: true,
    includeInNetWorth: false,
    notes: "Manual recurring bill.",
    status: "active",
    reviewDate: "2026-09-30",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "manual_salary_forecast",
    name: "Salary forecast",
    type: "manual_income",
    direction: "income",
    amount: 2850,
    currency: "GBP",
    dueDate: "2026-07-25",
    recurrence: { frequency: "monthly", interval: 1 },
    apr: null,
    minimumPayment: null,
    counterparty: "Employer",
    includeInCashflow: true,
    includeInNetWorth: false,
    notes: "Manual recurring income forecast.",
    status: "active",
    reviewDate: "2026-08-25",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "manual_housemate_contribution",
    name: "Housemate contribution",
    type: "manual_income",
    direction: "income",
    amount: 250,
    currency: "GBP",
    dueDate: "2026-07-01",
    recurrence: { frequency: "monthly", interval: 1 },
    apr: null,
    minimumPayment: null,
    counterparty: "Housemate",
    includeInCashflow: true,
    includeInNetWorth: false,
    notes: "Manual recurring income contribution.",
    status: "active",
    reviewDate: "2026-09-30",
    createdAt,
    updatedAt: createdAt,
  },
];

const totalAssets = calculateTotalAssets(mockAccounts, mockManualFinanceItems);
const totalLiabilities = calculateTotalLiabilities(
  mockAccounts,
  mockDebts,
  mockManualFinanceItems,
);

export const mockNetWorthSnapshots: NetWorthSnapshot[] = [
  {
    id: "nws_2026_06_30",
    userId,
    date: "2026-06-30",
    assetsTotal: totalAssets,
    liabilitiesTotal: totalLiabilities,
    netWorth: totalAssets - totalLiabilities,
    currency: "GBP",
    createdAt,
  },
];

export const mockAIInsights: AIInsight[] = [
  {
    id: "insight_weekly_001",
    userId,
    type: "weekly_review",
    title: "Flexible spending needs a light review",
    summary:
      "Safe-to-spend remains positive after upcoming bills, goal contributions, debt payments, and the minimum buffer.",
    evidence: [
      "Manual bills and future expenses are included in the cashflow view.",
      "Eating out has two flagged transactions in the current period.",
    ],
    assumptions: ["All figures are mock seed data.", "No Open Banking data is connected."],
    nextAction: "Review flexible spending before changing any budget.",
    status: "active",
    createdAt,
  },
];

export const mockAlerts: Alert[] = [
  {
    id: "alert_budget_eating_out",
    userId,
    type: "budget_pace_high",
    severity: "warning",
    title: "Eating out is ahead of pace",
    message: "Two recent transactions are pushing flexible spending higher than planned.",
    entityType: "category",
    entityId: "cat_eating_out",
    status: "new",
    createdAt,
  },
  {
    id: "alert_subscription_review",
    userId,
    type: "subscription_review",
    severity: "info",
    title: "Streaming bundle needs review",
    message: "The next payment is marked for review before becoming a confirmed subscription.",
    entityType: "subscription",
    entityId: "sub_streaming",
    status: "new",
    createdAt,
  },
];

export const mockFinanceData = {
  userProfile: mockUserProfile,
  accounts: mockAccounts,
  transactions: mockTransactionRecords,
  categories: mockCategories,
  budgets: mockBudgets,
  budgetPeriods: mockBudgetPeriods,
  bills: mockBills,
  subscriptions: mockSubscriptions,
  savingsGoals: mockSavingsGoals,
  debts: mockDebts,
  netWorthSnapshots: mockNetWorthSnapshots,
  aiInsights: mockAIInsights,
  alerts: mockAlerts,
  manualFinanceItems: mockManualFinanceItems,
};

const currentPeriod = mockBudgetPeriods[0];
const projectionPeriod = mockBudgetPeriods[1];
const asOfDate = "2026-06-30";
const nextPaydayDate = "2026-07-25";
const elapsedBudgetPeriodRatio = 1;

const plannedSavingsBeforePayday = mockSavingsGoals.reduce(
  (total, goal) => total + goal.monthlyContribution,
  0,
);

const currentCash = calculateTotalCurrentCash(mockAccounts, mockManualFinanceItems);
const billsDueBeforePayday = calculateBillsDueBeforePayday(
  mockBills,
  mockSubscriptions,
  mockManualFinanceItems,
  asOfDate,
  nextPaydayDate,
);
const debtPaymentsBeforePayday = calculateDebtPaymentsDueBeforePayday(
  mockDebts,
  mockManualFinanceItems,
  asOfDate,
  nextPaydayDate,
);
const projectionIncome = calculateMonthlyIncome(
  mockTransactionRecords,
  mockManualFinanceItems,
  projectionPeriod,
);
const projectionOutflows =
  calculateBillsDueBeforePayday(
    mockBills,
    mockSubscriptions,
    mockManualFinanceItems,
    projectionPeriod.startDate,
    projectionPeriod.endDate,
  ) +
  calculateDebtPaymentsDueBeforePayday(
    mockDebts,
    mockManualFinanceItems,
    projectionPeriod.startDate,
    projectionPeriod.endDate,
  ) +
  plannedSavingsBeforePayday +
  920;

export const dashboardSummary = {
  currentCash,
  safeToSpend: calculateSafeToSpendAmount({
    currentCash,
    billsDueBeforePayday,
    plannedSavingsBeforePayday,
    debtPaymentsBeforePayday,
    minimumBuffer: mockUserProfile.minimumBuffer,
    reservedGoalContributions: 0,
  }),
  billsDueBeforePayday,
  monthlyIncome: calculateMonthlyIncome(
    mockTransactionRecords,
    mockManualFinanceItems,
    currentPeriod,
  ),
  monthlySpending: calculateMonthlySpending(
    mockTransactionRecords,
    mockManualFinanceItems,
    currentPeriod,
  ),
  projectedMonthEndBalance: calculateProjectedMonthEndBalance({
    currentCash,
    expectedIncome: projectionIncome,
    plannedOutflows: projectionOutflows,
  }),
  totalAssets,
  totalLiabilities,
  netWorth: calculateNetWorth(mockAccounts, mockDebts, mockManualFinanceItems),
  debtSummary: calculateDebtSummary(mockDebts, mockManualFinanceItems),
  nextPayday: formatDateShort(nextPaydayDate),
  budgetStatus: "Mostly on track",
};

export const budgetHealth = calculateBudgetHealth(
  mockBudgets,
  mockTransactionRecords,
  mockCategories,
  currentPeriod,
  elapsedBudgetPeriodRatio,
);

export const upcomingBills = getUpcomingBillItems(
  mockBills,
  mockSubscriptions,
  mockManualFinanceItems,
  asOfDate,
  nextPaydayDate,
).map((item) => ({
  ...item,
  dueDateLabel: formatDateShort(item.dueDate),
}));

export const upcomingManualCashflowItems = getUpcomingManualCashflowItems(
  mockManualFinanceItems,
  asOfDate,
  projectionPeriod.endDate,
);

function categoryName(categoryId: string) {
  return mockCategories.find((category) => category.id === categoryId)?.name ?? "Other";
}

function accountName(accountId: string) {
  return mockAccounts.find((account) => account.id === accountId)?.name ?? "Mock account";
}

function transactionTone(transaction: Transaction): Tone {
  if (transaction.status === "needs_review") {
    return "warning";
  }

  if (transaction.flags.includes("ahead_of_pace")) {
    return "warning";
  }

  if (transaction.flags.includes("recurring")) {
    return "neutral";
  }

  return "good";
}

function transactionStatusLabel(transaction: Transaction) {
  if (transaction.status === "needs_review") {
    return "Needs review";
  }

  if (transaction.flags.includes("ahead_of_pace")) {
    return "Ahead of pace";
  }

  if (transaction.flags.includes("recurring")) {
    return "Recurring";
  }

  return "Reviewed";
}

export const mockTransactions = mockTransactionRecords.map((transaction) => ({
  id: transaction.id,
  date: formatDateShort(transaction.date),
  account: accountName(transaction.accountId),
  merchant: transaction.merchant,
  description: transaction.description,
  amount: transaction.amount,
  category: categoryName(transaction.categoryId),
  status: transactionStatusLabel(transaction),
  tone: transactionTone(transaction),
}));

export const recurringPayments = [
  ...mockBills.map((bill) => ({
    id: bill.id,
    name: bill.name,
    type: bill.essential ? "Essential bill" : "Bill",
    cadence: bill.recurrence.frequency,
    nextDue: formatDateShort(bill.dueDate),
    amount: bill.amount,
    status: "Confirmed",
    tone: "good" as const,
  })),
  ...mockSubscriptions.map((subscription) => ({
    id: subscription.id,
    name: subscription.name,
    type: "Subscription",
    cadence: subscription.recurrence.frequency,
    nextDue: formatDateShort(subscription.dueDate),
    amount: subscription.amount,
    status: subscription.status === "pending_review" ? "Needs review" : "Confirmed",
    tone: subscription.status === "pending_review" ? ("warning" as const) : ("neutral" as const),
  })),
  ...mockManualFinanceItems
    .filter((item) => item.type === "manual_bill" || item.type === "future_expense")
    .map((item) => ({
      id: item.id,
      name: item.name,
      type: item.type === "manual_bill" ? "Manual bill" : "Future expense",
      cadence: item.recurrence?.frequency ?? "one_off",
      nextDue: item.dueDate ? formatDateShort(item.dueDate) : "No date",
      amount: item.amount,
      status: "Manual",
      tone: "neutral" as const,
    })),
];

export const recurringPaymentSummary = {
  confirmedBills: mockBills.filter((bill) => bill.status === "confirmed").length,
  subscriptions: mockSubscriptions.length,
  needsReview: [
    ...mockSubscriptions.filter((subscription) => subscription.status === "pending_review"),
    ...mockManualFinanceItems.filter((item) => item.status === "pending_review"),
  ].length,
};

export const savingsGoals = mockSavingsGoals.map((goal) => ({
  ...goal,
  targetDate: formatDateShort(goal.targetDate),
  priority: `${goal.priority[0].toUpperCase()}${goal.priority.slice(1)}`,
  suggestedMonthlyContribution: goal.monthlyContribution,
  progress: calculateSavingsGoalProgress(goal),
}));

export const dashboardInsight = mockAIInsights[0];
